services:
  web:
    image: nginx:alpine-otel
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.variables.conf:/etc/nginx/templates/10-variables.conf.template:ro
      # 🔽 prod:
      # - ../dist/base:/var/www/html/base
      # - ../dist:/var/www/html
      # 🔽 dev:
      - ../public:/var/www/html

    environment:
      DB_HOST: 127.0.0.1
      DB_PORT: 8000
      FILE_HOST: 127.0.0.1
      FILE_PORT: 9000
      OTEL_EXPORTER_OTLP_ENDPOINT: "localhost:4317"

    ports:
      - 8000:80 # nginx
      - 7000:7000 # grafana

  php-fpm:
    image: webslab/filefind:latest
    volumes:
      # 🔽 prod:
      # - ../dist:/app/resources
      # 🔽 dev:
      - ../public:/app/resources

    network_mode: service:web

  surrealdb:
    image: surrealdb/surrealdb:v2.2.1
    command:
      - start
      - memory
      - -A
      - --no-banner
      - --user=root
      - --pass=root

    environment:
      SURREAL_LOG: none # none, full, error, warn, info, debug, trace
      SURREAL_TELEMETRY_PROVIDER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://127.0.0.1:4317"

    network_mode: service:web

  otel:
    image: grafana/otel-lgtm:0.9.0
    environment:
      GF_SERVER_HTTP_PORT: "7000"

    network_mode: service:web
